= Errata for *Pro Spring 6*

Hi guys, I am really thankful to all of you that have bought the book and have contributed to finding mistakes in it and in the code, and asking questions about details that seem unclear.

== Chapter 3: Introducing IoC and DI in Spring

'''

On **page 49**, in the note in the middle of the page, in the first sentence, there is a typo.

Original sentence:

`You might notice that the interface and class in this example have *np* type accessor.`

Correction:

`You might notice that the interface and class in this example have *no* type accessor.`

(Submitted by _Albert Attard_)

'''

On *page 60*, at the bottom of the page there is this statement The __ `@Autowired` annotation is not used to decorate the constructor... __, but Listing 13-3 shows the `@Autowired` annotation on the constructor. The warning box on the following page mentions that the annotation is redundant and why. However, keeping the annotation in Listing 13-3, even if not a grave technical error, might be confusing so this was an oversight on my part, that I will correct in the next edition.

(Submitted by _Nikolas Poniros_)

'''

On *page 66* the output in Listing 3-19 should be:

[source, log]
----
Name: John Mayer
Age: 40
Age in Seconds: 1241401112
Height: 1.92
Is Developer?: false
----

(Submitted by _Albert Attard_)

'''

On *page 84* there is a mistake in the paragraph before the `Explicit Bean Name Section`.

`context.getBeansOfType(String.class)` should be `context.getBeansOfType(SimpleBean.class)`

(Submitted by _Albert Attard_)

'''

On *page 86* the type for the `value()` and `name()` methods should be `String[]` as defined in the https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/context/annotation/Bean.java[ `@Bean` annotation source code].

(Submitted by _Albert Attard_)

'''

On *page 86*, in code Listing 3-49 and before class `NonSingletonDemo` is mentioned instead of  class `Singer`.

(Submitted by _Albert Attard_)

== Chapter 4: Advanced Spring Configuration and Spring Boot

'''
On **page 106**, there is a small typo. _Learning more about the Spring aplication context..._ should be _Learning more about the Spring ap**p**lication context..._

(Submitted by  _Nikolas Poniros_)

'''
On **page 114**, there is a small typo. The first paragraph under section title _Using the JSR-250 `@PostConstruct` Annotation_ , `Chapter 4` is being references. It should be `Chapter *3*`.

(Submitted by  _Nikolas Poniros_)

'''
On **page 116**, there is a small typo. The `2` footnote references should be in superscript.

(Submitted by  _Nikolas Poniros_)

'''
On **page 127**, there is a small typo. The caution box states that _Spring automatically calls the `getObject()` method is a bad practice call that method manually._ It should be _Spring automatically calls the `getObject()` method; is a bad practice *to* call that method manually._

(Submitted by  _Nikolas Poniros_)

'''
On **page 141**, there is a small typo. There is a space between `ReloadableResource` and `BundleMessageSource` which messes up the actual class name. Should be `ReloadableResourceBundleMessageSource`.

(Submitted by  _Nikolas Poniros_)

'''
On **page 143**, in Listing 4-28 the name of one of the message resource file shown in the comment is wrong. The listing shows `#labels_de_DE.properties`, should be `#labels_uk_UA.properties`.

(Submitted by _Albert Attard_)

'''
On **page 143**, in the description of `getMessage()` method the message used as example is `msg=The quick brown fox jumped over the lazy dog` and this doesn't match the msg in Listing 4-28. It should be `msg=Witnessing and not stopping evil is condoning it`.

Also, on **page 143**, in the description of `getMessage()` method, the `nameMsg` key value is shown as `My nameis {0} {1}`. It should be `My name is {0} {1}`

(Submitted by  _Nikolas Poniros_)

'''

On **page 147** under section `Considerations for Event Usage`, the statement _the update component explicitly notifies the cache that the user details have changed_ should be _the update component explicitly notifies the cache that the *product* details have changed_.

(Submitted by  _Nikolas Poniros_)

'''

On **page 149** there is this statement:

_Notice that for both the `file:` and `http:` protocols, Spring returns a `UrlResource` instance. Spring does include a `FileSystemResource` class, *thus* the `DefaultResourceLoader` does not use this class at all._

This statement is confusing, should be replaced with:

_Notice that for both the `file:` and `http:` protocols, Spring returns a `UrlResource` instance. Spring does include a `FileSystemResource` class, *albeit* the `DefaultResourceLoader` does not use this class at all._

(Submitted by  _Nikolas Poniros_)

'''

On **page 156** the output snippets at the bottom of the page. This was caused by a wrong import statement in the code. The import has now been corrected and the expected outputs are:

Running the `ProfileDemo` class with the JVM `-Dspring.profiles.active="kindergarten"` argument produces the following output:

[source, log]
----
DEBUG: AbstractEnvironment - Activating profiles [kindergarten]
INFO : ProfileDemo - Food: Milk
INFO : ProfileDemo - Food: Biscuits
----
This is exactly what the implementation of the kindergarten provider will produce for the lunch set. Now change the profile argument from the previous listing to high school (`-Dspring.profiles.active="highschool"`), and the output will change to the following:

[source, log]
----
DEBUG: AbstractEnvironment - Activating profiles [highschool]
INFO : ProfileDemo - Food: Coke
INFO : ProfileDemo - Food: Hamburger
INFO : ProfileDemo - Food: Fries
----
(Submitted by _Ahmed Hadaka_)

'''

=== Chapter 5: Spring AOP

'''

On **page 201** there is this statement:

_Consider the earlier example of the after-returning advice designed to catch weak keys generated by the `KeyGenerator` class._

This example was removed from the book because its complexity might distract from the advice implementation, but it was kept in the code repository. However, the above
statement should be replaced with _Consider the example of the after-returning advice designed to catch weak keys generated by the `*KeyGenerator*` class(example in the code repository, class `KeyGeneratorAdviceDemo`)._ in future editions of this book.

(Submitted by  _Nikolas Poniros_)

'''

On **page 209** there is this statement:

_Notice that we have used the same advice class as in the static pointcut example. However, in this example, only the first two calls to `sing({key})` should be advised. The dynamic check prevents the third call to `sing("E")` from being advised, and the static check prevents the `sing()` method from being advised._

This statement is somewhat confusing, mostly because of mentioning both static and dynamic advice. In future editions of this book, this statement should be changed to:

_Notice that we have used the same advice class(`DefaultPointcutAdvisor`) as in the static pointcut example. However, in this example, only the first two calls to `sing({key})` should be advised. The dynamic check prevents the third call to `sing("E")` from being advised, while the static check prevents any method but `sing()` method from being advised, ignoring the arguments altogether. _

(Submitted by  _Nikolas Poniros_)

'''

On **page 209**, Listing 5-14 is missing the `proxy.sing("c")` call output. This might have been intentional, to keep the output small. In future editions, the missing output will be mentioned.

(Submitted by  _Nikolas Poniros_)

'''

On **page 226**, the following statement:

_As you can see, when the `*sing*()` method is first invoked outside the control flow of the `test()` method, it is unadvised._

Should be replaced with

_As you can see, when the `*foo*()` method is first invoked outside the control flow of the `test()` method, it is unadvised._

(Submitted by  _Nikolas Poniros_)

'''

On **page 230**, the following statement:

_The first thing to notice in this example is the set of three private `MethodMatcher` implementations. `SingMethodMatcher` matches all methods that start with `*get*`._

Should be replaced with

The first thing to notice in this example is the set of three private `MethodMatcher` implementations. `SingMethodMatcher` matches all methods that start with `*si*`._

(Submitted by  _Nikolas Poniros_)

'''

On **page 230**, the following statement:

_`TalkMethodMatcher` is very specific and matches only the `talk()` method. This `MethodMatcher` is combined with `ComposablePointcut` by using `intersection()` for the third round for invocations._

Should be replaced with

_`RestMethodMatcher` matches only methods with names ending in`st`. This `MethodMatcher` is combined with `ComposablePointcut` by using `intersection()` for the third round for invocations._

(Submitted by  _Nikolas Poniros_)

'''

=== Chapter 6: Spring Data Access with JDBC

'''

On **page 311**, the following paragraph:

_Each time the `insertWithAlbum()` method is called, a new instance of `InsertSingerAlbum` is constructed because the `BatchSqlUpdate` class is not thread safe. Then we use it just like `SqlUpdate`. The main difference is that the `BatchSqlUpdate` class will queue up the insert operations and submit them to the database in batch._

I seem to have gotten my wires seriously crossed when I wrote this paragraph. It should be replaced in future revisions with:

_The `BatchSqlUpdate` class extends `SqlUpdate` and provides the capability to batch update operations. Is not thread safe, thus a new instance needs to be created for each use, or call `reset()` before reuse within the same thread._

(Submitted by  _Nikolas Poniros_)

'''

On **page 322**, int the following paragraph:

_Any code that might distract you from the TestContainers central configuration was stripped away from the `StoredFunctionV1Test**Test**` class, the class where the `TestContainersConfig` is declared. It was declared inside the test class because this is the only place where it is used._

The class name `StoredFunctionV1TestTestTest`, should be `StoredFunctionV1TestTest`.

(Submitted by  _Nikolas Poniros_)

'''

