insert into singer (id, first_name, last_name, birth_date) values (1, 'John', 'Mayer', '1977-10-16');
insert into singer (id, first_name, last_name, birth_date) values (2, 'Ben', 'Barnes', '1981-08-20');
insert into singer (id, first_name, last_name, birth_date) values (3, 'John', 'Butler', '1975-04-01');
insert into singer (id, first_name, last_name, birth_date) values (4, 'Eric', 'Clapton', '1945-03-30');
insert into singer (id, first_name, last_name, birth_date) values (5, 'B.B.', 'King', '1925-09-16');
insert into singer (id, first_name, last_name, birth_date) values (6, 'Jimi', 'Hendrix', '1942-11-27');
insert into singer (id, first_name, last_name, birth_date) values (7, 'Jimmy', 'Page', '1944-01-09');
insert into singer (id, first_name, last_name, birth_date) values (8, 'Eddie', 'Van Halen', '1955-01-26');
insert into singer (id, first_name, last_name, birth_date) values (9, 'Saul Slash', 'Hudson','1965-07-23');
insert into singer (id, first_name, last_name, birth_date) values (10, 'Stevie', 'Ray Vaughan','1954-10-03');
insert into singer (id, first_name, last_name, birth_date) values (11, 'David', 'Gilmour','1946-03-06');
insert into singer (id, first_name, last_name, birth_date) values (12, 'Kirk', 'Hammett', '1992-11-18');
insert into singer (id, first_name, last_name, birth_date) values (13, 'Angus', 'Young', '1955-03-31');
insert into singer (id, first_name, last_name, birth_date) values (14, 'Dimebag', 'Darrell','1966-08-20');
insert into singer (id, first_name, last_name, birth_date) values (15, 'Carlos', 'Santana','1947-07-20');
insert into singer (id, first_name, last_name, birth_date) values (16, 'Christian', 'Kane', '1972-06-27');
insert into singer (id, first_name, last_name, birth_date) values (17, 'Ella', 'Jane Fitzgerald', '1917-04-25');
insert into singer (id, first_name, last_name, birth_date) values (18, 'Billie', 'Holiday', '1917-04-07');
insert into singer (id, first_name, last_name, birth_date) values (19, 'Bessie', 'Smith', '1894-04-15');
insert into singer (id, first_name, last_name, birth_date) values (20, 'Peggy', 'Lee', '1920-05-26');
insert into singer (id, first_name, last_name, birth_date) values (21, 'Nina', 'Simone', '1933-02-21');
insert into singer (id, first_name, last_name, birth_date) values (22, 'Jackie', 'Paris', '1924-09-20');
insert into singer (id, first_name, last_name, birth_date) values (23, 'Nat', 'King cole', '1919-03-17');
insert into singer (id, first_name, last_name, birth_date) values (24, 'Cassandra', 'Wilson', '1955-12-04');
insert into singer (id, first_name, last_name, birth_date) values (25, 'Etta', 'Jones', '1928-11-25');
insert into singer (id, first_name, last_name, birth_date) values (26, 'Chet', 'Baker', '1929-12-23');
insert into singer (id, first_name, last_name, birth_date) values (27, 'Sarah', 'Vaughan', '1924-03-27');
insert into singer (id, first_name, last_name, birth_date) values (28, 'Ray', 'Charles', '1930-09-23');
insert into singer (id, first_name, last_name, birth_date) values (29, 'Dinah', 'Washington', '1924-08-29');
insert into singer (id, first_name, last_name, birth_date) values (30, 'Frank', 'Sinatra', '1915-12-12');
