GET http://localhost:8080/ch15/home
###

GET http://localhost:8080/ch15/singer/
Accept: application/xml
###

GET http://localhost:8080/ch15/singer/
Accept: application/json
###

GET http://localhost:8080/ch15/singer/1
###

GET http://localhost:8080/ch15/singer/1
Accept: application/xml
###

GET http://localhost:8080/ch15/singer/1
Accept: application/json
###